package gym.modelo.entidad;
// Generated 30/05/2015 09:23:09 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * AsistenciaCliente generated by hbm2java
 */
public class AsistenciaCliente  implements java.io.Serializable {


     private String idAsistenciaCliente;
     private Persona persona;
     private Usuario usuario;
     private Date fecha;
     private Date horaSalida;
     private String idContratoCliente;

    public AsistenciaCliente() {
    }

	
    public AsistenciaCliente(String idAsistenciaCliente) {
        this.idAsistenciaCliente = idAsistenciaCliente;
    }
    public AsistenciaCliente(String idAsistenciaCliente, Persona persona, Usuario usuario, Date fecha, Date horaSalida, String idContratoCliente) {
       this.idAsistenciaCliente = idAsistenciaCliente;
       this.persona = persona;
       this.usuario = usuario;
       this.fecha = fecha;
       this.horaSalida = horaSalida;
       this.idContratoCliente = idContratoCliente;
    }
   
    public String getIdAsistenciaCliente() {
        return this.idAsistenciaCliente;
    }
    
    public void setIdAsistenciaCliente(String idAsistenciaCliente) {
        this.idAsistenciaCliente = idAsistenciaCliente;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Date getHoraSalida() {
        return this.horaSalida;
    }
    
    public void setHoraSalida(Date horaSalida) {
        this.horaSalida = horaSalida;
    }
    public String getIdContratoCliente() {
        return this.idContratoCliente;
    }
    
    public void setIdContratoCliente(String idContratoCliente) {
        this.idContratoCliente = idContratoCliente;
    }




}


