package gym.modelo.entidad;
// Generated 30/05/2015 09:23:09 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * CategoriaContrato generated by hbm2java
 */
public class CategoriaContrato  implements java.io.Serializable {


     private String idCategoria;
     private String nombreCategoria;
     private BigDecimal descuento;
     private Set contratoClientes = new HashSet(0);

    public CategoriaContrato() {
    }

	
    public CategoriaContrato(String idCategoria) {
        this.idCategoria = idCategoria;
    }
    public CategoriaContrato(String idCategoria, String nombreCategoria, BigDecimal descuento, Set contratoClientes) {
       this.idCategoria = idCategoria;
       this.nombreCategoria = nombreCategoria;
       this.descuento = descuento;
       this.contratoClientes = contratoClientes;
    }
   
    public String getIdCategoria() {
        return this.idCategoria;
    }
    
    public void setIdCategoria(String idCategoria) {
        this.idCategoria = idCategoria;
    }
    public String getNombreCategoria() {
        return this.nombreCategoria;
    }
    
    public void setNombreCategoria(String nombreCategoria) {
        this.nombreCategoria = nombreCategoria;
    }
    public BigDecimal getDescuento() {
        return this.descuento;
    }
    
    public void setDescuento(BigDecimal descuento) {
        this.descuento = descuento;
    }
    public Set getContratoClientes() {
        return this.contratoClientes;
    }
    
    public void setContratoClientes(Set contratoClientes) {
        this.contratoClientes = contratoClientes;
    }




}


