package gym.modelo.entidad;
// Generated 30/05/2015 09:23:09 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ContratoCliente generated by hbm2java
 */
public class ContratoCliente  implements java.io.Serializable {


     private String idContratoCliente;
     private Persona persona;
     private TipoContrato tipoContrato;
     private Usuario usuario;
     private CategoriaContrato categoriaContrato;
     private Double montoTotal;
     private Date fechaInicio;
     private Date fechaFin;
     private String estado;
     private Date fechaRegistro;
     private Set movimientos = new HashSet(0);

    public ContratoCliente() {
    }

	
    public ContratoCliente(String idContratoCliente) {
        this.idContratoCliente = idContratoCliente;
    }
    public ContratoCliente(String idContratoCliente, Persona persona, TipoContrato tipoContrato, Usuario usuario, CategoriaContrato categoriaContrato, Double montoTotal, Date fechaInicio, Date fechaFin, String estado, Date fechaRegistro, Set movimientos) {
       this.idContratoCliente = idContratoCliente;
       this.persona = persona;
       this.tipoContrato = tipoContrato;
       this.usuario = usuario;
       this.categoriaContrato = categoriaContrato;
       this.montoTotal = montoTotal;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
       this.estado = estado;
       this.fechaRegistro = fechaRegistro;
       this.movimientos = movimientos;
    }
   
    public String getIdContratoCliente() {
        return this.idContratoCliente;
    }
    
    public void setIdContratoCliente(String idContratoCliente) {
        this.idContratoCliente = idContratoCliente;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public TipoContrato getTipoContrato() {
        return this.tipoContrato;
    }
    
    public void setTipoContrato(TipoContrato tipoContrato) {
        this.tipoContrato = tipoContrato;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public CategoriaContrato getCategoriaContrato() {
        return this.categoriaContrato;
    }
    
    public void setCategoriaContrato(CategoriaContrato categoriaContrato) {
        this.categoriaContrato = categoriaContrato;
    }
    public Double getMontoTotal() {
        return this.montoTotal;
    }
    
    public void setMontoTotal(Double montoTotal) {
        this.montoTotal = montoTotal;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public Set getMovimientos() {
        return this.movimientos;
    }
    
    public void setMovimientos(Set movimientos) {
        this.movimientos = movimientos;
    }




}


