package gym.modelo.entidad;
// Generated 30/05/2015 09:23:09 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Movimiento generated by hbm2java
 */
public class Movimiento  implements java.io.Serializable {


     private String idMovimiento;
     private Persona persona;
     private Usuario usuario;
     private ContratoCliente contratoCliente;
     private Date fecha;
     private String detalle;
     private BigDecimal totalRecibido;

    public Movimiento() {
    }

	
    public Movimiento(String idMovimiento) {
        this.idMovimiento = idMovimiento;
    }
    public Movimiento(String idMovimiento, Persona persona, Usuario usuario, ContratoCliente contratoCliente, Date fecha, String detalle, BigDecimal totalRecibido) {
       this.idMovimiento = idMovimiento;
       this.persona = persona;
       this.usuario = usuario;
       this.contratoCliente = contratoCliente;
       this.fecha = fecha;
       this.detalle = detalle;
       this.totalRecibido = totalRecibido;
    }
   
    public String getIdMovimiento() {
        return this.idMovimiento;
    }
    
    public void setIdMovimiento(String idMovimiento) {
        this.idMovimiento = idMovimiento;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public ContratoCliente getContratoCliente() {
        return this.contratoCliente;
    }
    
    public void setContratoCliente(ContratoCliente contratoCliente) {
        this.contratoCliente = contratoCliente;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getDetalle() {
        return this.detalle;
    }
    
    public void setDetalle(String detalle) {
        this.detalle = detalle;
    }
    public BigDecimal getTotalRecibido() {
        return this.totalRecibido;
    }
    
    public void setTotalRecibido(BigDecimal totalRecibido) {
        this.totalRecibido = totalRecibido;
    }




}


