package gym.modelo.entidad;
// Generated 30/05/2015 09:23:09 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Persona generated by hbm2java
 */
public class Persona  implements java.io.Serializable {


     private String idPersona;
     private String nombre;
     private String apellidos;
     private String dni;
     private String sexo;
     private String telefono;
     private String direccion;
     private Usuario usuario;
     private Set asistenciaClientes = new HashSet(0);
     private Set movimientos = new HashSet(0);
     private Set contratoClientes = new HashSet(0);

    public Persona() {
    }

	
    public Persona(String idPersona) {
        this.idPersona = idPersona;
    }
    public Persona(String idPersona, String nombre, String apellidos, String dni, String sexo, String telefono, String direccion, Usuario usuario, Set asistenciaClientes, Set movimientos, Set contratoClientes) {
       this.idPersona = idPersona;
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.dni = dni;
       this.sexo = sexo;
       this.telefono = telefono;
       this.direccion = direccion;
       this.usuario = usuario;
       this.asistenciaClientes = asistenciaClientes;
       this.movimientos = movimientos;
       this.contratoClientes = contratoClientes;
    }
   
    public String getIdPersona() {
        return this.idPersona;
    }
    
    public void setIdPersona(String idPersona) {
        this.idPersona = idPersona;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Set getAsistenciaClientes() {
        return this.asistenciaClientes;
    }
    
    public void setAsistenciaClientes(Set asistenciaClientes) {
        this.asistenciaClientes = asistenciaClientes;
    }
    public Set getMovimientos() {
        return this.movimientos;
    }
    
    public void setMovimientos(Set movimientos) {
        this.movimientos = movimientos;
    }
    public Set getContratoClientes() {
        return this.contratoClientes;
    }
    
    public void setContratoClientes(Set contratoClientes) {
        this.contratoClientes = contratoClientes;
    }




}


