package gym.modelo.entidad;
// Generated 30/05/2015 09:23:09 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Servicio generated by hbm2java
 */
public class Servicio  implements java.io.Serializable {


     private String idServicio;
     private String nombreServicio;
     private BigDecimal costoServ;

    public Servicio() {
    }

	
    public Servicio(String idServicio) {
        this.idServicio = idServicio;
    }
    public Servicio(String idServicio, String nombreServicio, BigDecimal costoServ) {
       this.idServicio = idServicio;
       this.nombreServicio = nombreServicio;
       this.costoServ = costoServ;
    }
   
    public String getIdServicio() {
        return this.idServicio;
    }
    
    public void setIdServicio(String idServicio) {
        this.idServicio = idServicio;
    }
    public String getNombreServicio() {
        return this.nombreServicio;
    }
    
    public void setNombreServicio(String nombreServicio) {
        this.nombreServicio = nombreServicio;
    }
    public BigDecimal getCostoServ() {
        return this.costoServ;
    }
    
    public void setCostoServ(BigDecimal costoServ) {
        this.costoServ = costoServ;
    }




}


