package gym.modelo.entidad;
// Generated 30/05/2015 09:23:09 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * TipoContrato generated by hbm2java
 */
public class TipoContrato  implements java.io.Serializable {


     private String idTipoContrato;
     private String nombre;
     private BigDecimal nuemerDias;
     private Set contratoClientes = new HashSet(0);

    public TipoContrato() {
    }

	
    public TipoContrato(String idTipoContrato) {
        this.idTipoContrato = idTipoContrato;
    }
    public TipoContrato(String idTipoContrato, String nombre, BigDecimal nuemerDias, Set contratoClientes) {
       this.idTipoContrato = idTipoContrato;
       this.nombre = nombre;
       this.nuemerDias = nuemerDias;
       this.contratoClientes = contratoClientes;
    }
   
    public String getIdTipoContrato() {
        return this.idTipoContrato;
    }
    
    public void setIdTipoContrato(String idTipoContrato) {
        this.idTipoContrato = idTipoContrato;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public BigDecimal getNuemerDias() {
        return this.nuemerDias;
    }
    
    public void setNuemerDias(BigDecimal nuemerDias) {
        this.nuemerDias = nuemerDias;
    }
    public Set getContratoClientes() {
        return this.contratoClientes;
    }
    
    public void setContratoClientes(Set contratoClientes) {
        this.contratoClientes = contratoClientes;
    }




}


