package gym.modelo.entidad;
// Generated 30/05/2015 09:23:09 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private String idUsuario;
     private Persona persona;
     private String usuario;
     private String password;
     private String tipo;
     private String estado;
     private Set asistenciaClientes = new HashSet(0);
     private Set contratoClientes = new HashSet(0);
     private Set movimientos = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(Persona persona) {
        this.persona = persona;
    }
    public Usuario(Persona persona, String usuario, String password, String tipo, String estado, Set asistenciaClientes, Set contratoClientes, Set movimientos) {
       this.persona = persona;
       this.usuario = usuario;
       this.password = password;
       this.tipo = tipo;
       this.estado = estado;
       this.asistenciaClientes = asistenciaClientes;
       this.contratoClientes = contratoClientes;
       this.movimientos = movimientos;
    }
   
    public String getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(String idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getAsistenciaClientes() {
        return this.asistenciaClientes;
    }
    
    public void setAsistenciaClientes(Set asistenciaClientes) {
        this.asistenciaClientes = asistenciaClientes;
    }
    public Set getContratoClientes() {
        return this.contratoClientes;
    }
    
    public void setContratoClientes(Set contratoClientes) {
        this.contratoClientes = contratoClientes;
    }
    public Set getMovimientos() {
        return this.movimientos;
    }
    
    public void setMovimientos(Set movimientos) {
        this.movimientos = movimientos;
    }




}


